export const INITIAL_GAME_DATA = {
  frames: [
    {
      name: "Frame 1",
      frameScore: 0,
      firstThrowScore: null,
      secondThrowScore: null,
      thirdThrowSCore: null,
      isSpare: false,
      isStrike: false,
      isDoneScoring: false,
      canHaveThirdThrow: false,
    },
    {
      name: "Frame 2",
      frameScore: 0,
      firstThrowScore: null,
      secondThrowScore: null,
      thirdThrowSCore: null,
      isSpare: false,
      isStrike: false,
      isDoneScoring: false,
      canHaveThirdThrow: false,
    },
    {
      name: "Frame 3",
      frameScore: 0,
      firstThrowScore: null,
      secondThrowScore: null,
      thirdThrowSCore: null,
      isSpare: false,
      isStrike: false,
      isDoneScoring: false,
      canHaveThirdThrow: false,
    },
    {
      name: "Frame 4",
      frameScore: 0,
      firstThrowScore: null,
      secondThrowScore: null,
      thirdThrowSCore: null,
      isSpare: false,
      isStrike: false,
      isDoneScoring: false,
      canHaveThirdThrow: false,
    },
    {
      name: "Frame 5",
      frameScore: 0,
      firstThrowScore: null,
      secondThrowScore: null,
      thirdThrowSCore: null,
      isSpare: false,
      isStrike: false,
      isDoneScoring: false,
      canHaveThirdThrow: false,
    },
    {
      name: "Frame 6",
      frameScore: 0,
      firstThrowScore: null,
      secondThrowScore: null,
      thirdThrowSCore: null,
      isSpare: false,
      isStrike: false,
      isDoneScoring: false,
      canHaveThirdThrow: false,
    },
    {
      name: "Frame 7",
      frameScore: 0,
      firstThrowScore: null,
      secondThrowScore: null,
      thirdThrowSCore: null,
      isSpare: false,
      isStrike: false,
      isDoneScoring: false,
      canHaveThirdThrow: false,
    },
    {
      name: "Frame 8",
      frameScore: 0,
      firstThrowScore: null,
      secondThrowScore: null,
      thirdThrowSCore: null,
      isSpare: false,
      isStrike: false,
      isDoneScoring: false,
      canHaveThirdThrow: false,
    },
    {
      name: "Frame 9",
      frameScore: 0,
      firstThrowScore: null,
      secondThrowScore: null,
      thirdThrowSCore: null,
      isSpare: false,
      isStrike: false,
      isDoneScoring: false,
      canHaveThirdThrow: false,
    },
    {
      name: "Frame 10",
      frameScore: 0,
      firstThrowScore: null,
      secondThrowScore: null,
      thirdThrowSCore: null,
      isSpare: false,
      isStrike: false,
      isDoneScoring: false,
      canHaveThirdThrow: true,
    },
  ],
  totalGameScore: 0,
};
